### ISSUE TITLE
No endpoint definition could be found for: GET '/'

### ISSUE THREAD

**Issue by phs** [seomoz/interpol#27]
Consider this endpoint

``` yaml

---
name: hello_world
route: /hello
method: GET
definitions:
  - message_type: request
    versions: ["1.0"]
    schema: {}
    examples: []
  - message_type: response
    versions: ["1.0"]
    status_codes: ["2xx", "404"]
    schema:
      type: object
      properties:
        greetings:
          description: A salutation.
          type: string

    examples:
      - greetings: Hello, world!
```

And this app:

``` ruby
require 'sinatra/base'
require 'json'
require 'config'
require 'interpol/response_schema_validator'

module MozscapeAPI
  class Application < Sinatra::Base

    before do
      content_type 'application/json'
    end

    use Interpol::ResponseSchemaValidator

    get '/hello' do
      JSON.dump greetings: 'Hello, world!'
    end

  end
end
```

This works hunky-dory.  If, however, I change the Sinatra route in both the app and endpoint to `/`, then requesting the root yields this thing:

```
Interpol::NoEndpointDefinitionFoundError at /
No endpoint definition could be found for: GET '/'
file: response_schema_validator.rb location: validate! line: 42

138. /usr/local/var/rbenv/versions/1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb in service
      si.service(req, res)
94. /usr/local/var/rbenv/versions/1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb in run
          server.service(req, res)
191. /usr/local/var/rbenv/versions/1.9.3-p429/lib/ruby/1.9.1/webrick/server.rb in block in start_thread
          block ? block.call(sock) : run(sock)
```
